### ISSUE TITLE
關於字形輔助碼的建議蒐集

### ISSUE THREAD

**Issue by imper0502** [imper0502/rime-double-bopomo#1]
# 使用輔助碼的主要目的有二：
## 1. 分辨同音字，如：他她它牠
> ![分辨他她它牠](https://images2.imgbox.com/95/cb/oiUxkBiC_o.jpg)
## 2. 減少選字，甚至精確選字：
> ![以速成倉頡當輔助碼](https://images2.imgbox.com/44/b1/i66BedKn_o.jpg)
## 問題
目前我有嘗試直接用倉頡 &行列10的第一碼當輔助碼，效果都不錯，但是第二碼要怎麼取？是個大問題。
- 我目前實驗，速成（倉頡直接取首尾）效果差：
> ![最常用的「的」怎麼取都不好……](https://images2.imgbox.com/b9/68/30yvJQlB_o.jpg)
> ![倉+cj](https://images2.imgbox.com/06/55/Wq6mLHvK_o.jpg)
> ![行+cj](https://images2.imgbox.com/13/19/XPOhNQWU_o.jpg)
- 行列10，雖然只有是個基本筆劃，效果卻和倉頡差不多：
> ![的+array10](https://images2.imgbox.com/ac/cb/n9DduhcJ_o.jpg)
> ![倉+array10](https://images2.imgbox.com/da/d8/ZmsgemGk_o.jpg)
> ![行+array10](https://images2.imgbox.com/90/c4/3hRSfXCe_o.jpg)
但我對形碼輸入法不瞭解（我只會一點點的大新倉頡），請大家給我建議。

目前考慮方案：
- 倉頡編碼
- 行列基本字根
- 行列輸入法
- 四角編碼
- 三角輸入法

P.S. 不過我接下來四個月有事情，要到2020，3月、4月才會有空。先給大家抱歉。

**Comment by GJRobert** [comment]
我是用嘸蝦米的，嘸蝦米兩碼以下的漢字也是有輔助碼，可參考：
[行易有限公司 :: 嘸蝦米輸入法「截長補短」](http://boshiamy.com/tutorial_beginner.php?page=4#tab_tab2)

**Comment by imper0502** [comment]
> 我是用嘸蝦米的，嘸蝦米兩碼以下的漢字也是有輔助碼，可參考：
> [行易有限公司 :: 嘸蝦米輸入法「截長補短」](http://boshiamy.com/tutorial_beginner.php?page=4#tab_tab2)

謝謝你的建議，不過前兩碼代表音節，所以沒有辦法用嘸蝦米的輔助碼規則……

若是直接輸入另一個輸入法，那麼輔助碼就沒有意義了。因為實際上只要一套輸入法就能打字了。
包括倉頡、行列輸入法都有這個問題。

我現在的想法是借用或簡化其他輸入法的字根，再加上一個足夠簡單地「輔助碼取碼規則」來實現功能（不是使用「輸入法取碼規則」）。

不過，現有的雙拼輔助碼，如：鶴形、小牛字形，也如無蝦米一樣，使用了音托的字根，我會把無蝦米列入考慮。

**Comment by GJRobert** [comment]
嗯嗯，我瞭解前兩碼代表注音的音節「聲+韻」，您是要用第三甚至第四來降低選字率對嗎
那還是先不管我說的嘸蝦米尾碼，試試嘸蝦米的首尾碼來當三、四碼？如果是ㄘㄤ的話，可能
```
倉	ch + ao
藏	ch + rr
蒼	ch + ro
艙	ch + zo
滄	ch + wo
蔵	ch + rrv
傖	ch + po
……
```

**Comment by imper0502** [comment]
> 嗯嗯，我瞭解前兩碼代表注音的音節「聲+韻」，您是要用第三甚至第四來降低選字率對嗎
> 那還是先不管我說的嘸蝦米尾碼，試試嘸蝦米的首尾碼來當三、四碼？如果是ㄘㄤ的話，可能
> 
> ```
> 倉	ch + ao
> 藏	ch + rr
> 蒼	ch + ro
> 艙	ch + zo
> 滄	ch + wo
> 蔵	ch + rv
> 傖	ch + po
> ……
> ```

基本上，目前看來，直接用任何一種的形碼輸入法的【頭+尾】都不是很好。

我現在想了幾個點：
1. 蒼滄艙傖，這些有邊讀邊的字，如果用首尾碼當輔助碼，第二碼都一樣。此外，音碼的部分已經代表了「倉」，輔助碼再強調一次，實在是重複了。
2. 我可能要先定義至多 650（25*26= 650）字的二碼字，也就是不論如何也不用輔助碼的字。這樣我就不用煩惱「的得」的輔助碼重碼了。
3. 目前有想了一個不錯的取碼方案，大致上是從左上角開始，順時針取碼，取第一碼、第二碼。這個取碼方法單獨使用重碼很多，但配上音碼後，反而合適。
# 但缺點是我要自己編碼……

**Comment by imper0502** [comment]
> 嗯嗯，我瞭解前兩碼代表注音的音節「聲+韻」，您是要用第三甚至第四來降低選字率對嗎
> 那還是先不管我說的嘸蝦米尾碼，試試嘸蝦米的首尾碼來當三、四碼？如果是ㄘㄤ的話，可能
> 
> ```
> 倉	ch + ao
> 藏	ch + rr
> 蒼	ch + ro
> 艙	ch + zo
> 滄	ch + wo
> 蔵	ch + rrv
> 傖	ch + po
> ……
> ```
做了一個「雙碼注音+嘸蝦米第一碼」 試試看吧！
[雙碼注音+嘸蝦米第一碼](https://www.dropbox.com/s/l1zq6jwe4lnpaq5/double-bopomo%2Bboshiamy.rar?dl=0)
空白鍵選字，Tab輸出到螢幕。嚴格三碼或嚴格兩碼（不能一下三碼、一下兩碼）。

**Comment by GJRobert** [comment]
我開始試用了～挺有趣的。平常都打嘸蝦米，現在特地來學雙碼注音的鍵位表。
您編碼辛苦了！！！

- 有些字真的兩碼或三碼就直接出字了，沒有重碼字，不用選。
- 「67890ABCDE」選字，但我按不出後面的 ABCDE 耶，還是 ABCDE 實際上是沒有用的？
- 有些讀音就算加了嘸蝦米第一碼，重碼字還是不少，甚至要翻到第二頁
- 重碼字順序的權重如果可以參照一些資料來排過，看可否把一般人最常用的字放到最前面， 或是動態依照使用者選字的偏好來調整權重（印象中這兩種功能 Rime 都有）。

**Comment by imper0502** [comment]
> * 「67890ABCDE」選字，但我按不出後面的 ABCDE 耶，還是 ABCDE 實際上是沒有用的？

原版的1\~5是聲調，所以用67890選字，A\~E沒有作用。（我習慣一頁5字）
加嘸蝦米版本，1~5沒有被使用，rime會 *忽略* 替代選字鍵。所以還是用1234567890選字。

> * 有些讀音就算加了嘸蝦米第一碼，重碼字還是不少，甚至要翻到第二頁

目前的實驗，嘸蝦米是重碼最高的沒錯。如果有詞庫會好很多。（這個‘+嘸蝦米實驗版’是純單字，沒有詞的）

> * 重碼字順序的權重如果可以參照一些資料來排過，看可否把一般人最常用的字放到最前面， 或是動態依照使用者選字的偏好來調整權重（印象中這兩種功能 Rime 都有）。

原本的純雙拼是用 「腳本翻譯器」，是按照常用字排序的
但加嘸蝦米版本改用「碼表翻譯器」，多了一些功能（下一碼提示、造詞等等），但排序就變成依編碼（a-z）了。
不說目前我是不到三個月要考研究所的考生，排序、編碼這些東東可是大工程啊！（偉哉regex\~偉哉vim\~）

**Comment by GJRobert** [comment]
> > * 有些讀音就算加了嘸蝦米第一碼，重碼字還是不少，甚至要翻到第二頁
> 
> 目前的實驗，嘸蝦米是重碼最高的沒錯。如果有詞庫會好很多。（這個‘+嘸蝦米實驗版’是純單字，沒有詞的）

哇，那感覺我提供「嘸蝦米第一碼」是不是變成餿主意了 XD 真不好意思。
table_translator 支援詞庫嗎？（不好意思我對 Rime 引擎的運作很多都還在瞭解中）
 
> > * 重碼字順序的權重如果可以參照一些資料來排過，看可否把一般人最常用的字放到最前面， 或是動態依照使用者選字的偏好來調整權重（印象中這兩種功能 Rime 都有）。
> 
> 原本的純雙拼是用 「腳本翻譯器」，是按照常用字排序的
> 但加嘸蝦米版本改用「碼表翻譯器」，多了一些功能（下一碼提示、造詞等等），但排序就變成依編碼（a-z）了。
> 不說目前我是不到三個月要考研究所的考生，排序、編碼這些東東可是大工程啊！（偉哉regex~偉哉vim~）

真的很感謝你耶～至少我覺得，「以注音符號為基礎的雙拼」+「轉譯為 26 字母的鍵位」這方向很不錯，對臺灣人而言熟悉，對華語/Mandarin/「普通話」雙拼使用者而言也是一個頗有效率的選擇。

至於研發第 3、4 碼就真的是大工程了，我想當初嘸蝦米發明人劉重次先生對此也是煞費苦心，才去設計很多「有趣」的規則來盡量減少選字。現在你要創新一個輸入方案，要花很多的心思嘗試是一定的。

學業為重，祝順利！

**Comment by flier268** [comment]
如果是用部首來做為第三碼跟第四碼呢?
如果是木部，第三四碼就是木的拼音，這樣就不需要再多記一套東西了
畢竟中文的造字規則裡面，很多字的差別就只在於部首不同而已

**Comment by IanHo79** [comment]
不曉得這個網址的試算表文件檔內的列表內容，能否對double-bopomo專案開發者的表格設計發想有幫助？
國語一字多音審訂表再製表格檔
https://sites.google.com/site/ianho7979/roctwmoepolyphone_unofficial_third-party_reproduction
