### ISSUE TITLE
wiki 上的安裝方法，可新增 iOS 的 iRIME

### ISSUE THREAD

**Issue by sjackwu** [imper0502/rime-double-bopomo#12]
底下這個方法確定可行

https://www.ptt.cc/bbs/IME/M.1572622340.A.FEA.html
`iRime在設定時，要用到電腦。
  選擇內建方案「地球拼音」，接著確定 iPhone 跟電腦都連線到相同的 Wifi 後，開啟
電腦傳檔，連線到手機，下載「default.custom.yaml」到電腦。
  在電腦上編輯這個檔案，在「- terra_pinyin」這一行底下按相同的格式加入
  「- double_bopomo」後，存檔。
  最後上傳「default.custom.yaml」和「double_bopomo.schema.yaml」到手機。
  上傳前記得先刪除舊的「default.custom.yaml」，再開始上傳。
  回到手機，按下部署，完成。
`

**Comment by imper0502** [comment]
感謝回報，我都忘記我之前寫的東西了，現在不用重寫真是太好了。
