### ISSUE TITLE
強制分音節簡拼？

### ISSUE THREAD

**Issue by GJRobert** [imper0502/rime-double-bopomo#2]
〔以下討論 double-bopomo `master` 分支的試用問題〕
`master` 分支是用 script_translator，所以好處是可以利用到 Rime 本身詞庫來自動智慧選詞（不知道我有沒有理解錯誤）。比方說我們 double_bopomo 打字，`hjar` 4 鍵連打，就會出現 `ㄏㄤ ㄓㄡ`，且有首選詞「杭州」；打 `hjarxihu` 馬上就有「杭州西湖」可選，非常方便。

不知道 Rime 的 schema 設計上，有沒有可能讓我更偷懶，打 `h'a'x'h` 出現 `ㄏ ㄓ ㄒ ㄏ`，通通都只打聲母（我知道但是需要分音節的符號，不然無法分辨是韻母還是下一音節的聲母），就出現「杭州西湖」？實際上按鍵數一樣，但是我可能就不用打韻母，通通無腦打聲母就好，這有點像強制簡拼？

我在找目前 double-bopomo 有沒有設計強制分音節的符號，但沒有試出來。打空白鍵就是直接出首選字；schema 裡有 `delimiter: " '"`，但 `'` 目前沒有什麼效用的樣子，或是它的效果和我想的不一樣。

我也試著把 `express_editor` 改為 `fluid_editor`，但與此無關，變成「語句流」只是改變了出字和上字的鍵而已，按空白鍵仍然不是強制分音節，而是一樣出字。

不知道是不是 double_bopomo 已經可以強制提前結束音節，還是如果怎樣調整就可以呢？

**Comment by imper0502** [comment]
可以做到，具體而言：
1. 要清除 key blinding 按鍵綁定，讓「'」恢復原本定義（大部分的rime使用者都有對該鍵的設定個人定義，這是我沒有把簡拼當成預設功能的主要原因）
2. 先修改`speller/alphabet: "bpmfdtnlgkhjqxvwarzcsiuyeo"`，為：
`speller/alphabet: "bpmfdtnlgkhjqxvwarzcsiuy'eo"`
接著，在speller/algebra中加入：
` \- abbrev/^(.).+$/$1'/`
這樣一來，聲母才會被視為可以被「'」分開的合法音節，但順序較後，不會影響正常雙拼。
3. 雙碼拼音預設使用聲調簡拼，數字1~5是聲調，可以直接聲母+聲調輸入字詞。不必做1. 2.的修改。

**Comment by GJRobert** [comment]
很感謝你，對 Rime 的瞭解非常透徹，讓我獲益良多！

預設的 3. 很棒，1. 2. 我有機會也來試試！雖然我是蝦米人，但覺得雙碼注音搭配詞庫、記憶常用詞、簡拼，熟起來的話幾乎都兩碼兩碼不用選字可能也會蠻快的，我可能考慮在行動裝置上取代 Gboard 或 iOS 內建注音。（如果 trime 和 iRime 夠給力的話）

（這則留言都是用雙碼注音 master 摸著打出來的，目前還沒背起來）

**Comment by imper0502** [comment]
@GJRobert 
現在我在新版本加入了「；鍵強制簡拼的功能」
、「shift+對應按鍵=對應韻母」歡迎試用新版本。
而且現在雙拼、簡拼也可以在一般情況下混著打了。

> 「；」鍵可以自行改成其他按鍵，目前是依照Rime的慣例
