### ISSUE TITLE
鍵位圖少了「ㄨㄞ」韻 + 程式產生鍵位圖

### ISSUE THREAD

**Issue by GJRobert** [imper0502/rime-double-bopomo#3]
目前的 double-bopomo-keyboard-layout.jpg 上我沒找到「ㄨㄞ」，看了一下 CIN 表發現是編在 `G`～看要不要更新一下。

Btw，我找找看有沒有人做「自動產生鍵位圖」的工具，還真的有！
我開了一個空白的 26 鍵底圖：[Keyboard Layout Editor](http://www.keyboard-layout-editor.com/#/gists/6605377d2fb45b14fb09c5a537c1b102)

**Comment by GJRobert** [comment]
Keyboard Layout Editor 真的超．好．玩．的
我試了，文字欄位接受 `<br>` 換行，這樣才能實現「ㄩㄝ」等注音符號直排。

或許 @imper0502 可以調調看喜歡的版型、顏色

**Comment by imper0502** [comment]
> 目前的 double-bopomo-keyboard-layout.jpg 上我沒找到「ㄨㄞ」，看了一下 CIN 表發現是編在 `G`～看要不要更新一下。

剛剛看了一下，我真的忘啦，謝謝你的提醒。
不過Keyboard Layout Editor，大概要等我明年3月才有空做了。

**Comment by imper0502** [comment]
![雙碼注音-qwerty-鍵盤佈局](https://user-images.githubusercontent.com/17744001/83837806-0f935400-a72a-11ea-88fa-341915a1539a.png)

@GJRobert 畫完了！

**Comment by GJRobert** [comment]
媠(suí)！漂亮！恭喜(kiong-hí)！讚啦
