### ISSUE TITLE
無調版 .cin 有不少重複的內容

### ISSUE THREAD

**Issue by gugod** [imper0502/rime-double-bopomo#4]
例, 自 85 行開始

```
hs 好
hs 好
uw 為
uw 為
oj 上
oj 上
lh 來
lh 來
jb 就
xq 學
```

其他還有不少

透過 macos openvanilla 來使用的話, 會在選字窗出現重複選項:

![螢幕快照 2020-06-05 01 06 34](https://user-images.githubusercontent.com/4970/83789097-d4ad0400-a6c8-11ea-80bb-361759fd8036.png)

**Comment by imper0502** [comment]
這個部分我是手動去重複的，有時間我會再檢查一次。

這個問題是出在破音字去音調的時候發生的。目前我並沒有較好的方法去處理它，很抱歉。

**Comment by imper0502** [comment]
@gugod 
我最後發現，notepad++有內建去除重複行的功能，我成功使用它去除重複的項目。
